openapi: 3.0.0
info:
  title: ncb-accounts-api1
  description: API to move the logs data from source to target.
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/NCB-NOUS/ncb-accounts-api1/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://Ncbaccountsspringbootapi-env.eba-ewvv4mpi.us-east-1.elasticbeanstalk.com
  description: API In Beanstalk
security:
- oAuth2ClientCredentials: []
paths:
  /accounts/{accountid}/monthlystatements/move:
    post:
      tags:
      - Account Statements
      summary: Endpoint to move the monthly statements.
      description: Move the monthly statements from source to destination
      operationId: movemonthlystatements
      parameters:
      - name: accountid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          x-disabled-for-amazon-gateway:
            example: "12352"
          example: null
      - name: monthandyear
        in: query
        required: true
        style: form
        explode: true
        schema:
          pattern: ^\d{2}-\d{4}$
          type: string
          x-disabled-for-amazon-gateway:
            example: 02-2022
          example: null
      responses:
        "200":
          description: Success Data Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
              example:
                Message: 02-2022.txt has been copied to the target location 12345/02-2022.txt
        "400":
          description: Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                Message: Bad Request.
        "401":
          description: Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                Message: Unauthorized.
        "404":
          description: Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                Message: No file present in the source.
        "500":
          description: Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                Message: Internal server error at the source.
      x-amazon-apigateway-integration:
        integration.request.querystring.page: method.request.querystring.page
        integration.request.querystring.type: method.request.querystring.type
        passthroughBehavior: when_no_match
        httpMethod: POST
        uri: http://Ncbaccountsspringbootapi-env.eba-ewvv4mpi.us-east-1.elasticbeanstalk.com/accounts/{accountid}/monthlystatements/move
        requestParameters:
          integration.request.path.accountid: method.request.path.accountid
        responses:
          default:
            statusCode: "200"
        type: http
        
  /api/accounts/{accountid}:
    get:
      tags:
      - Account information
      summary: Endpoint to retrive account information.
      description: Retrive's account information.
      operationId: getaccountdetails
      parameters:
      - name: accountid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          x-disabled-for-amazon-gateway:
            example: "12352"
          example: null
      - name: appName
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Success Data Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        "400":
          description: Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                Errormessage: Bad Request.
        "401":
          description: Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                Message: Unauthorized.
        "404":
          description: Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                Message: Account not found.
        "500":
          description: Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                Message: Internal server error at the source.
      x-amazon-apigateway-integration:
        passthroughBehavior: when_no_match
        httpMethod: GET
        uri: http://Ncbaccountsspringbootapi-env.eba-ewvv4mpi.us-east-1.elasticbeanstalk.com/api/accounts/{accountid}
        requestParameters:
          integration.request.path.accountid: method.request.path.accountid
        responses:
          default:
            statusCode: "200"
        type: http
    post:
      tags:
      - Account information
      summary: Endpoint to retrive account information.
      description: Retrive's account information.
      operationId: postaccountdetails
      parameters:
      - name: accountid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          x-disabled-for-amazon-gateway:
            example: "12352"
          example: null
      - name: app_client_id
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          x-disabled-for-amazon-gateway:
            example: fhgf366739dsa897f
          example: null
      responses:
        "200":
          description: Success Data Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        "400":
          description: Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                Errormessage: Bad Request.
        "401":
          description: Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                Message: Unauthorized.
        "404":
          description: Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                Message: Account not found.
        "500":
          description: Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                Message: Internal server error at the source
      x-amazon-apigateway-integration:
        passthroughBehavior: when_no_match
        httpMethod: POST
        uri: http://Ncbaccountsspringbootapi-env.eba-ewvv4mpi.us-east-1.elasticbeanstalk.com/api/accounts/{accountid}
        requestParameters:
          integration.request.path.accountid: method.request.path.accountid
        responses:
          default:
            statusCode: "200"
        type: http
components:
  schemas:
    Account:
      type: object
      properties:
        iban:
          type: string
          x-disabled-for-amazon-gateway:
            example: DE27100777770209299700
          example: null
        bban:
          type: string
          x-disabled-for-amazon-gateway:
            example: BARC12345612345678
          example: null
        pan:
          type: string
          x-disabled-for-amazon-gateway:
            example: "5409050000000000"
          example: null
        maskedPan:
          type: string
          x-disabled-for-amazon-gateway:
            example: 123456xxxxxx1234
          example: null
        msisdn:
          type: string
          x-disabled-for-amazon-gateway:
            example: +49 170 1234567
          example: null
        currency:
          type: string
          x-disabled-for-amazon-gateway:
            example: EUR
          example: null
    Errors:
      type: object
      properties:
        Errormessage:
          type: string
          x-disabled-for-amazon-gateway:
            example: error
          example: null
    Success:
      type: object
      properties:
        Successmessage:
          type: string
          x-disabled-for-amazon-gateway:
            example: Success
          example: null
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      description: for more info visit https://nous.security
      flows:
        clientCredentials:
          tokenUrl: https://dev-57990228.okta.com/oauth2/aus1oajcuqOB2LvSJ5d7/v1/token
          scopes: {}
x-aws-api-id: 1ejjudvc01